# Generated by Django 5.0.1 on 2024-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_payload', models.JSONField()),
                ('stream_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreatedPostEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('event_sourcing.postevents',),
        ),
        migrations.CreateModel(
            name='PostUpdatedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('event_sourcing.postevents',),
        ),
        migrations.CreateModel(
            name='ReadyForReviewEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('event_sourcing.postevents',),
        ),
    ]
