# Generated by Django 5.0.1 on 2024-04-03 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_sourcing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='stream_id',
            field=models.UUIDField(default=uuid.UUID('3b214350-976b-4d57-b947-7e8c47a6b94b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postevents',
            name='stream_id',
            field=models.UUIDField(editable=False),
        ),
    ]
