# Generated by Django 5.0.1 on 2024-03-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CreatedPostEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cqrs.postevents',),
        ),
        migrations.CreateModel(
            name='UpdatedPostEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cqrs.postevents',),
        ),
    ]
