# Generated by Django 5.0.1 on 2024-03-06 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqrs', '0002_postevents_createdpostevent_updatedpostevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatedPostEvent',
        ),
        migrations.CreateModel(
            name='PostUpdatedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cqrs.postevents',),
        ),
        migrations.CreateModel(
            name='ReadyForReviewEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cqrs.postevents',),
        ),
        migrations.AddField(
            model_name='postevents',
            name='stream_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
